# Generated by Django 3.1 on 2020-09-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(blank=True, null=True, to='core.ItemVariation'),
        ),
    ]
