# Generated by Django 3.1 on 2020-09-07 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Biling'), ('S', 'Shipping')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_address',
            field=models.CharField(default='alig road', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='alig road', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=454454, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(blank=True, to='core.ItemVariation'),
        ),
    ]
